### ISSUE TITLE
Compute intersection of local conceptlist

### ISSUE THREAD

**Issue by Tarotis** [concepticon/pyconcepticon#39] opened 2022-10-07 08:39 UTC
Hello everybody,

is there an implemented way of running the intersection command against a local conceptlist that is not part of CONCEPTICON, but succesfully mapped?

Currently, I try to run the following command:
`concepticon intersection Swadesh-1955-100 Pano-Takana/blumpanotacana/etc/Conceptlists/Alviano-1957-448.tsv`

Alviano-1957-448 is a conceptlist with the following columns: 

> ID	NUMBER	WORD	CONCEPTICON_ID	CONCEPTICON_GLOSS

However, I receive the following error message:
```
(concepticon) blum@lingn18 Projects % concepticon intersection Swadesh-1955-100 Pano-Takana/blumpanotacana/etc/Conceptlists/Alviano-1957-448.tsv
INFO    concepticon/concepticon-data at /Users/blum/Library/Application Support/cldf/concepticon
Traceback (most recent call last):
  File "/usr/local/bin/concepticon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/__main__.py", line 62, in main
    return args.main(args) or 0
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/commands/intersection.py", line 22, in run
    format_set_operation(args.repos.intersection(*get_conceptlist(args)))
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/api.py", line 543, in intersection
    return list(self._set_operation('intersection', *clids, **kw))
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/api.py", line 524, in _set_operation
    for c, lists in compare_conceptlists(self, *clids, **kw):
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 315, in compare_conceptlists
    for c in clist.concepts.values():
  File "/usr/local/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 255, in concepts
    for item in self.metadata:
  File "/usr/local/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 234, in metadata
    return self.tg.tables[0]
  File "/usr/local/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 226, in tg
    tg = TableGroup.from_file(md)
  File "/usr/local/lib/python3.9/site-packages/csvw/metadata.py", line 1039, in from_file
    res = cls.fromvalue(data or get_json(fname))
  File "/usr/local/lib/python3.9/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.TableGroup>", line 39, in __init__
  File "/usr/local/lib/python3.9/site-packages/csvw/metadata.py", line 1402, in converter_tables
    res.append(Table.fromvalue(vv) if isinstance(vv, dict) else vv)
  File "/usr/local/lib/python3.9/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.Table>", line 46, in __init__
  File "/usr/local/lib/python3.9/site-packages/csvw/metadata.py", line 1166, in __attrs_post_init__
    raise ValueError('url property is required for Tables')
ValueError: url property is required for Tables
```

What works: 
`concepticon intersection Swadesh-1955-100 Swadesh-1952-200`

How can I fix my command or the conceptlist so I can compute the intersection?

**Comment by xrotwang** [comment] 2022-10-07 08:57
The latest `csvw` package requires tables in the metadata to have a `url` property - as the CSVW spec dictates. Some of the metadata files in `concepticondata/conceptlists` may not yet have these.

**Comment by xrotwang** [comment] 2022-10-07 09:00
What does the metadata file for `Pano-Takana/blumpanotacana/etc/Conceptlists/Alviano-1957-448.tsv` look like?

**Comment by Tarotis** [comment] 2022-10-07 09:25
It did not have a metadata, as the list is not part of Concepticon and never needed the metadata before. Is there some automated utility to create this metadata file or do di need to copy/paste/adapt every time?

I now set this up and run into the next problem: `pyconcepticon` requires me to have a `GLOSS` and `ENGLISH` column. However, I don't understand the reasoning behind this requirement. As I have the concepts in other languages, even if I were to add `GLOSS`, there would not be an `ENGLISH` column. According to my workflow with Mattis, this would only be added if the concept was given in English also in the original file. Everything else should be explicitly marked as `GLOSS`. For the time-being, I added dummy-columns `GLOSS` and `ENGLISH` and added a dummy value `a` in all rows. The intersection runs just fine. Hence my question: Can the requirement for those two columns be removed?

**Comment by Tarotis** [comment] 2022-10-07 09:26
``` 
File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 315, in compare_conceptlists
    for c in clist.concepts.values():
  File "/usr/local/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 261, in concepts
    res.append(Concept(list=self, attributes=attributes, **kw))
  File "<attrs generated init pyconcepticon.models.Concept>", line 14, in __init__
  File "/usr/local/lib/python3.9/site-packages/pyconcepticon/models.py", line 122, in valid_concept
    raise ValueError('fields gloss *and* english missing: %s' % instance)
```

**Comment by xrotwang** [comment] 2022-10-07 09:31
Oh, `fields gloss *and* english missing` is supposed to mean that you at least need one - with content in this column.

**Comment by xrotwang** [comment] 2022-10-07 09:34
When the list doesn't have custom metadata, `pyconcepticon` uses a default: https://github.com/concepticon/pyconcepticon/blob/master/src/pyconcepticon/conceptlist-metadata.json
Since this default **has** a `url` property for the table (now), you might be running an older version of `pyconcepticon`?

**Comment by Tarotis** [comment] 2022-10-07 09:52
I run `pyconcepticon-2.8.0`, which has the file you refer to. But somehow it does not seem to get called?

Ok, that seems reasonable. For my specific reason right now (check intersections in order to prepare final concept list for a database) I will not add a gloss right now, but the dummy column does the trick. Once the list is finalized I will add the glosses.

**Comment by LinguList** [comment] 2022-10-07 11:03
So the issue is solved then?

**Comment by Tarotis** [comment] 2022-10-07 11:52
While I can compute the intersection if I provide the metadata file, the open question remains why the default metadata file does not get called. So I wouldn't say it's completely solved.

**Comment by xrotwang** [comment] 2022-10-07 12:03
I'm somewhat hesitant to look into this right now, when we might be close to moving to Concepticon 3 (including a new version of pyconcepticon) where quite a few things will change anyway.

**Comment by Tarotis** [comment] 2022-10-07 12:08
As I know how to work around, that is totally fine with me. Do we leave this open in order to check once the new version is out?

**Comment by xrotwang** [comment] 2022-10-07 12:37
I think we can close this issue since it isn't only about this topic anyway.

**Closed** 2022-10-07 13:18 UTC

**Comment by LinguList** [comment] 2022-10-07 19:33
For the intersection of several lists, one can also -- maybe easier -- just do the intersection calculation from Python, using the pyconcepticon API to fetch existing lists, and fetching the relevant Concepticon IDs from the not-yet-added list by loading the TSV with csvw's UnicodeReader.

**Comment by Tarotis** [comment] 2022-10-10 08:07
Additionally, this yields the possibility to easily retrieve the concepts that are _not_ shared by the lists. I will probably proceed like this.
